### ISSUE TITLE
very slow to pack/unpack integer array

### ISSUE THREAD

**Issue by Orbots** [kmsquire/MsgPack.jl#11]
Julia 0.4.1
CentOS 6

Compared to a float array, integer array is brutally slow.  Note the 72 million allocations...

julia> bigun = rand(1000000);                                            
                                                                         
julia> @time MsgPack.pack(bigun);                                        
WARNING: uint32(x) is deprecated, use UInt32(x) instead.                 
 in depwarn at deprecated.jl:73                                          
 in uint32 at deprecated.jl:50                                           
 in pack at /dd/home/mewert/.julia/v0.4/MsgPack/src/MsgPack.jl:287       
 in pack at /dd/home/mewert/.julia/v0.4/MsgPack/src/MsgPack.jl:173       
while loading no file, in expression starting on line 155                
  0.262886 seconds (316 allocations: 17.622 MB, 1.16% gc time)           
                                                                         
julia> @time MsgPack.pack(bigun);                                        
  0.257133 seconds (102 allocations: 17.614 MB)                          
                                                                         
julia> bigun = collect(1:1000000);                                       
                                                                         
julia> @time MsgPack.pack(bigun);                                        
WARNING: uint32(x) is deprecated, use UInt32(x) instead.                 
 in depwarn at deprecated.jl:73                                          
 in uint32 at deprecated.jl:50                                           
 in pack at /dd/home/mewert/.julia/v0.4/MsgPack/src/MsgPack.jl:287       
 in pack at /dd/home/mewert/.julia/v0.4/MsgPack/src/MsgPack.jl:173       
while loading no file, in expression starting on line 155                
WARNING: uint32(x) is deprecated, use UInt32(x) instead.                 
 in depwarn at deprecated.jl:73                                          
 in uint32 at deprecated.jl:50                                           
 in pack at /dd/home/mewert/.julia/v0.4/MsgPack/src/MsgPack.jl:204       
 in pack at /dd/home/mewert/.julia/v0.4/MsgPack/src/MsgPack.jl:293       
 in pack at /dd/home/mewert/.julia/v0.4/MsgPack/src/MsgPack.jl:173       
while loading no file, in expression starting on line 155                
107.134147 seconds (72.01 M allocations: 598.657 GB, 14.76% gc time)

**Comment by kmsquire** [comment]
Hi @Orbots, any chance you can take a stab at fixing this?  Fixing the deprecation warnings would be a good start--they often introduce slowdowns--although there may be deeper issues.  I won't have time to look at this closely for a while.

**Comment by Orbots** [comment]
Sure.  I'll take a stab at it.  I'm pretty new to Julia, but that code looks fairly straight-forwards.
Thanks.
- Michael 


    On Sunday, November 22, 2015 7:03 AM, Kevin Squire <notifications@github.com> wrote:
 

 Hi @Orbots, any chance you can take a stab at fixing this? Fixing the deprecation warnings would be a good start--they often introduce slowdowns--although there may be deeper issues. I won't have time to look at this closely for a while.—
